version: '3.8'

services:
  backend:
    image: backend-image
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - APP_ENV=development

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./data:/var/lib/mysql