version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=banking
      - MYSQL_USER=backend
      - MYSQL_PASSWORD=backend_mysql
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
    volumes:
      - ./.data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge