name: "banking_app"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
    networks:
      - backend
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=banking
      - MYSQL_USER=backend
      - MYSQL_PASSWORD=backend_mysql
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge